### ISSUE TITLE
Could you please provide your source code of your paper?

### ISSUE THREAD

**Issue by vhientran** [yubowen-ph/segment#1]
Could you please provide your source code for your paper? Thank you so much.

**Comment by vhientran** [comment]
Hi @yubowen-ph , if possible, please provide your source code of your paper in IJCAI 2019. Thank you so much.

**Comment by yubowen-ph** [comment]
Sorry for the late reply, I will upload the code in two days.

**Comment by vhientran** [comment]
Thanks in advance for your help.

**Comment by vhientran** [comment]
Hi @yubowen-ph , sorry for disturbing you, but I am interested in your paper and want to reproduce some experiments. Could you please upload your source code? Thank you.

**Comment by yubowen-ph** [comment]
Sorry again, because other papers are being prepared recently, so I delayed uploading code. Now the code has been uploaded, I have sorted out the code, and some data files have not been uploaded, I will complete as soon as possible.

**Comment by vhientran** [comment]
Thank you so much.
